import "../styles/globals.css";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="h-screen overflow-hidden bg-red-500">{children}</body>
		</html>
	);
}
