/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

declare global {
    interface Window {
        __TAURI_INVOKE__<T>(cmd: string, args?: Record<string, unknown>): Promise<T>;
    }
}

// Function avoids 'window not defined' in SSR
const invoke = () => window.__TAURI_INVOKE__;

export function recordAudio() {
    return invoke()<null>("record_audio")
}

export function getConfig() {
    return invoke()<Config>("get_config")
}

export function setConfigSavePath(savePath: string) {
    return invoke()<Config>("set_config_save_path", { savePath })
}

export function getAcapFiles() {
    return invoke()<AcapFile[]>("get_acap_files")
}

export type Config = { config_file_path: string; save_path: string; recording_duration_in_secs: number }
export type AcapFile = { name: string; path: string }
